export const BASE_API = `${process.env.NEXT_PUBLIC_API_URL}/api`;
//TODO REMOVE THIS TOKEN ONCE LOGIN IS IMPLEMENTED
export const AUTH_TOKEN =
  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2MTU3MzA2MSwianRpIjoiMjE2NDRmMWItNzE2ZS00MzlhLTg2MjQtMjY3OTkxOWFiMWVjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFkbWluIiwibmJmIjoxNzYxNTczMDYxLCJjc3JmIjoiMTE4MjM1ZjEtZTk4OS00MjA3LTliNGQtZGQzNTIyYWJkZGFhIiwiZXhwIjoxNzYyODY5MDYxfQ.03AYzPFNz_bcLYvRLdNCKnfA4ot4XVwXXK9qMh3U83M";

export const LocalStorageKeys = {
  HIDE_COMPLETED: "hideCompletedGoals",
} as const;
